server:
  port: 8080

spring:
  profiles:
    active: druid,mybatis
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/static/img/

pagehelper:
  helper-dialect: mysql

<<<<<<< HEAD
=======
logging:
  level:
    top:
      philxin:
        mapper: debug
>>>>>>> 3a183e752bbc41d8ec6b43d9a745181a614d54f3
